USE_YOOMONEY: True
YOOMONEY_TOKEN: 
YOOMONEY_WALLET: 

USE_HELEKET: True
HELEKET_MERCHANT_UUID: 
HELEKET_API_KEY: 

CHANNEL_USERNAME: 
CHANNEL_ID: 

BOT_TOKEN: 
ADMIN_ID: 

DEBUG_MODE: False